apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: configmap-test
  namespace: default
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
     matchLabels:
       app: configmap-test
  template:
    metadata:
      labels:
         app: configmap-test
    spec:
      volumes:
        - name: demo
          configMap:
             name: myconfigmap
             items:
              - key: 
                path:              
      containers:
        - image: eu.gcr.io/microservices-2020/configmap:latest
          name: configmap-test
          imagePullPolicy: Always
          ports:
           - containerPort: 8080
             protocol: TCP
          env:
            - name: CONFIG_MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: myconfigmap
                  key: test.message
          volumeMounts:
            - name: demo
              mountPath: /mydata        
---         
apiVersion: v1
kind: Service
metadata:
   name: configmap-test
   namespace: default
   labels:
      name: configmap-test
spec:
   ports:
     - port: 8080
       targetPort: 8080
       protocol: TCP
   selector:
      app: configmap-test
   type: LoadBalancer
          
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stat
spec:
  